---
title: "MusselModel_Execute"
author: 'By: Claire Gonzales'
date: "2023-06-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)

library(tidyverse)
library(here)
library(paletteer)
library(ggplot2)
library(pracma)
```

# Mussel model

## Import Data
```{r}
#loading data
celldata <- read.csv(here("data", "bivalve_model", "celldata4.csv"))

```

```{r}
# create time variables
year_Oct2Mar <- seq(as.Date("2014-10-01"), as.Date("2016-03-31"), by = "day")
startdate <- as.Date("2014-10-01")
harvestcycle <- 365
days <- seq(startdate, by = "day", length.out = harvestcycle + 2)
resetdate <- as.Date("2015-04-01")
row <- which(year_Oct2Mar == resetdate)[1]

for (i in seq_along(days)) {
  while (days[i] > year_Oct2Mar[length(year_Oct2Mar)]) {
    days[i] <- year_Oct2Mar[row]
    row <- row + 1
  }
}
```

## Mussel derivative
```{r}
mussel_derivative <- function(T, N) {
  # GLOBAL VARIABLES
  Temps <- global_Temps
  mlds <- global_mlds
  Vs <- global_Vs
  Fs <- global_Fs
  Time <- global_Time
  
  # STATE VARIABLES
  mE <- N[1]  # Reserve biomass (molC)
  L_w <- N[2]  # Physical length (molC)
  MR <- N[3]  # Reproductive biomass (molC)
  F <- N[4]  # POC concentration (molC/cm3)
  n <- N[5]  # Time-dependent abundance of mussels in the farm modified by 
             # mortality rate (dn) in units of (# indiv.)
  
  # ENVIRONMENTAL VARIABLES
  # Interpolate using cubic spline
  Temp <- approxfun(Time, Temps, method = "pchip")(T)
  V <- approxfun(Time, Vs, method = "pchip")(T)
  mld <- approxfun(Time, mlds, method = "pchip")(T)
  F_in <- approxfun(Time, Fs, method = "pchip")(T)
  
  # STATIC PARAMETERS
  # Rate parameter values given at reference temperature of 283K
  v_ref <- 0.01359  # Energy conductance rate cm/d
  kM_ref <- 0.00447539  # Maintenance rate coeff 1/d
  maint_ratio <- 0.446888
  yEX <- 0.696818  # Yield of reserves from food (Cmole/Cmole; depends on food quality)
  yVE <- 0.878007  # Yield of structure from reserves
  deltam <- 0.1989  # Aspect ratio; see notes on size measures
  kappa <- 0.9283  # Fraction of reserves committed to growth + somatic maintenance
  kappar <- 0.95  # Conversion efficiency of reserves to gonad biomass
  Mvdensity <- 0.0041841  # Density of structure molC/cm3
  Ehp <- 97.41  # Maturity at puberty, J
  mu_E <- 550000  # Chemical potential of reserves, J/mol
  Lp <- 0.753047  # Structural length at puberty, cm
  Jxmax <- 0.0000783383  # Max surface specific feeding rate Cmoles/d cm2 for detrital C (addmypet)
  
  # For T conversion
  Ta <- 3243
  Tref <- 293
  
  # TEMPERATURE DEPENDENT PARAMETERS
  # Conversion function to calculate rate parameters for actual temperature
  Arrh <- exp((Ta/Tref) - (Ta/Temp))
  
  v <- Arrh * v_ref  # Temperature-adjusted energy conductance rate (cm/d)
  v_w <- v / deltam  # Temperature-adjusted physical length conversion rate (cm/d)
  Mvdensity_w <- Mvdensity * deltam^3
  Lp_w <- Lp / deltam  # Shell length at puberty (approx 1.2 cm)
  kM <- kM_ref * Arrh  # Temperature-adjusted maintenance rate coeff (1/d)
  jEM <- 1 * kM / yVE  # 1.4672; kM/yVE [maintenance rate coeff/yield of structure from reserves] (1/d)
  kJ <- maint_ratio * jEM * yVE  # = maint_ratio * kM [maintenance ratio * maintenance coefficient]
  
  # FUNCTIONAL RESPONSE
  # Farm dimensions
  farm_area <- 1000 * mld  # Cross-sectional area of farm in m2
  
  # Food competition
  r <- V * farm_area * 10000  # V(cm/d) * farm_area(m2) * 10000(cm2/m2) = (cm3/d)
  supply <- F_in * r  # F_in(molC/cm3) * r(cm3/d) = (molC/d)
  Fh <- 1.21e-8  # Half saturation constant (molC/cm3)
  f <- F / (Fh + F)  # Scaled functional response
  Jx <- Jxmax * L_w^2 * f  # Scaled individual rate of food consumption (molC/d)
  consumption <- n * Jx  # Total food consumption by whole mussel population (molC/d)
  dF <- supply - consumption - r * F
  
  # GROWTH EQUATIONS
  ME <- Mvdensity_w * mE * L_w^3
  if (kappa * v_w * mE > jEM * L_w) {
    # There is growth.
    dmE <- yEX * Jx / (Mvdensity_w * L_w^3) - v_w * mE / L_w  # Reserve dynamics (mol reserve C/mol structural C time)
    dL_w <- (kappa * v_w * mE - jEM * L_w) / (3 * kappa * mE + 3 / yVE)  # Shell growth
    if (L_w >= Lp_w) {
      Jcr <- kappar * ((1 - kappa) * mE * Mvdensity_w * (v_w * L_w^2 + yVE * jEM * L_w^3) /
        (kappa * mE * yVE + 1) - kJ * Ehp / mu_E)  # Gonad production rate (mol C/time)
    } else {
      Jcr <- 0
    }
  } else {
    if (v_w * mE > jEM * L_w) {
      # Reserve mobilization rate greater than somatic maintenance rate
      dmE <- yEX * Jx / (Mvdensity_w * L_w^3) - v_w * mE / L_w
      dL_w <- 0
      if (L_w >= Lp_w) {
        Jcr <- kappar * (Mvdensity_w * L_w^3 * (mE * v_w / L_w - jEM) - kJ * Ehp / mu_E)
        # Jcr is negative when maturity maintenance demands exceed
        # energy commitment to reproduction + maturity rate. THIS IS
        # A DEBATABLE CHOICE.
        if (Jcr < 0) {
          # dF <- 0
          print("Animal is starving; Gonads are resorped for maturity maintenance")
          print("Discuss with Roger or Erik if this happens frequently")
          if (MR < 0) {
            # dF <- 0
            Jcr <- 0
            print("WARNING: maturity maintenance is not fully paid")
            print("Results not reliable after this point")
          }
        }
      } else {
        Jcr <- 0
        if (Mvdensity_w * L_w^3 * (mE * v_w / L_w - jEM) < kJ * Ehp / mu_E) {
          print("WARNING: Juvenile may not mature properly")
          print("Results may not be reliable")
          print("Code needs to be changed to include maturation dynamics")
          print("See Roger or Erik")
        }
      }
    } else {
      dL_w <- 0
      Jcr <- 0
      if (L_w >= Lp_w) {
        if (MR > 0) {
          dmE <- yEX * Jx / (Mvdensity_w * L_w^3) - v_w * mE / L_w
          Jcr <- Mvdensity_w * L_w^3 * (v_w * mE / L_w - jEM) - kJ * Ehp / mu_E
          # assuming resorption conversion efficiency of 1
          print("Animal is starving; gonad resorption for maintenance")
          print("See Roger or Erik")
        } else {
          dmE <- yEX * Jx / (Mvdensity_w * L_w^3) - jEM
          print("Animal is starving; extra reserve mobilization to pay somatic maintenance")
          print("This is a debatable choice; Standard DEB prescribes death")
          print("See Erik or Roger")
          if (ME < 0) {
            dmE <- 0
            print("Animal starved to death")
          }
        }
      } else {
        dmE <- yEX * Jx / (Mvdensity_w * L_w^3) - jEM
        print("Animal is starving; extra reserve mobilization to pay somatic maintenance")
        print("This is a debatable choice; Standard DEB prescribes death")
        print("See Erik or Roger")
        if (ME < 0) {
          dmE <- 0
          print("Animal starved to death")
        }
      }
    }
  }
  dn <- 0  # Currently no mortality; Alternative: dn <- -0.0005 * n * (1 - (L_w / 12))
            # Calculation: 15% annual mortality rate (FAO); .15/300 = (probability of death/day)
            # Logistically size-dependent.
  
  output <- c(dmE, dL_w, Jcr, dF, dn)
  return(output)
}

```



## Mussel ODE Solve
```{r}
mussel_odeSolve <- function(cellno, celldata, days) {
  # Interpolate to get daily values for Temp, Vs, F, mld (so datasets match 'Time')
  year_Oct2Mar <- seq(as.Date("2014-10-01"), as.Date("2016-03-31"), by = "day")
  growPeriod <- length(days) - 1
  dayno <- which(days[1] == year_Oct2Mar)[1]
  
  # Make environmental parameters global for use in the derivative function
  mld_monthly <- celldata[cellno, 4:21]
  mld_daily <- interp1(1:18, mld_monthly, 1:.0311:18, method = "pchip")
  mlds <- mld_daily[dayno:dayno + growPeriod]
  
  Temp_monthly <- celldata[cellno, 22:39] + 273
  Temp_daily <- interp1(1:18, Temp_monthly, 1:.0311:18, method = "pchip")
  Temps <- Temp_daily[dayno:dayno + growPeriod]
  
  F_monthly <- celldata[cellno, 58:75] / 12e9
  F_daily <- interp1(1:18, F_monthly, 1:.0311:18, method = "pchip")
  Fs <- F_daily[dayno:dayno + growPeriod]
  
  V_monthly <- celldata[cellno, 40:57] * 8640000
  V_daily <- interp1(1:18, V_monthly, 1:.0311:18, method = "pchip")
  Vs <- V_daily[dayno:dayno + growPeriod]
  
  # Set time range/length of harvest cycle
  Time <- days
  
  # Set initial conditions
  L_w_init <- 0.03
  mE_init <- (4.24e-10 / 3.22e-10)
  MR_init <- 0
  F_init <- Fs[1]
  n_init <- 100 * 13000 * 100
  
  Init <- c(mE_init, L_w_init, MR_init, F_init, n_init)
  
  # ODE Solver
  ode_derivative <- function(t, N) {
    mussel_derivative(N, t, mlds, Temps, Fs, Vs)
  }
  
  T <- ode23(ode_derivative, Time, Init, atol = 1e-7, rtol = 1e-7)$xout
  
  # Derived Values (weights of product)
  deltam <- 0.1989
  Mvdensity <- 0.0041841
  Mvdensity_w <- Mvdensity * deltam^3
  LW <- T[, 2]
  MV <- 12 * Mvdensity_w * LW^3
  ME <- 12 * Mvdensity_w * T[, 1] * LW^3
  MR <- 12 * T[, 3]
  M <- MV + ME + MR
  Indiv <- T[, 5]
  C_content <- 0.034
  TM <- Indiv * M / (1000 * C_content)
  Mwet <- M / C_content
  
  # Available Food
  Fdens <- T[, 4] * 12e9
  
  # Functional Response
  Fh <- 1.21e-8
  f <- T[, 4] / (Fh + T[, 4])
  
  # Physical Conditions
  Temperature <- interp1(Time, Temps, T[, 1], method = "pchip") - 273
  MixedLayerDepth <- interp1(Time, mlds, T[, 1], method = "pchip")
  F_Ambient <- interp1(Time, Fs, T[, 1], method = "pchip") * 12e9
  CurrentSpeed <- interp1(Time, Vs / 86400, T[, 1], method = "pchip")
  
  return(list(T, TM, Indiv, MV, ME, MR, M, Mwet, LW, Fdens, F_Ambient, f, Temperature, MixedLayerDepth, CurrentSpeed))
}

mussel_derivative <- function(N, t, mlds, Temps, Fs, Vs) {
  mE <- N[1]
  L_w <- N[2]
  MR <- N[3]
  F <- N[4]
  n <- N[5]
  
  # Constants and parameters
  yEX <- 1  # reserve flux efficiency (J_X / J_E) (-)
  Jx <- 0  # food intake (J/d)
  jEM <- 0.002  # somatic maintenance rate (J/d)
  Ehp <- 3.75e5  # maturity threshold (J)
  kJ <- 1e8  # maturation rate (1/d)
  v_w <- 0.05  # energy conductance (cm/d)
  Lp_w <- 15  # maximum length (cm)
  
  # Derivatives
  dF <- 0
  if (L_w >= Lp_w) {
    if (MR > 0) {
      dmE <- yEX * Jx / (mlds[t] * L_w^3) - v_w * mE / L_w
      Jcr <- mlds[t] * L_w^3 * (v_w * mE / L_w - jEM) - kJ * Ehp / mu_E
      # assuming resorption conversion efficiency of 1
      print("Animal is starving; gonad resorption for maintenance")
      print("See Roger or Erik")
    } else {
      dmE <- yEX * Jx / (mlds[t] * L_w^3) - jEM
      print("Animal is starving; extra reserve mobilization to pay somatic maintenance")
      print("This is a debatable choice; Standard DEB prescribes death")
      print("See Erik or Roger")
      if (mE < 0) {
        dmE <- 0
        print("Animal starved to death")
      }
    }
  } else {
    dmE <- yEX * Jx / (mlds[t] * L_w^3) - jEM
    print("Animal is starving; extra reserve mobilization to pay somatic maintenance")
    print("This is a debatable choice; Standard DEB prescribes death")
    print("See Erik or Roger")
    if (mE < 0) {
      dmE <- 0
      print("Animal starved to death")
    }
  }
  
  dn <- 0
  
  output <- c(dmE, dL_w, Jcr, dF, dn)
  return(output)
}

```





## Execute Lookup Table or Single Cell
```{r}
# prompt
Ans0 <- readline(prompt = 'Create look-up table (T) or evaluate single cell (S)? (T/S)\n')
assert <- function(test, message) {
  if (!test) {
    stop(message)
  }
}
assert(Ans0 == 'T' || Ans0 == 'S', 'Please enter "T" or "S"')
tic()
```

Lookup Table/Single Cell
```{r}
# Lookup Table

if (Ans0 == 'T') {
  yield <- rep(0, length(celldata))
  Wets <- matrix(NA, nrow = length(celldata), ncol = harvestcycle + 2)
  ProblemCells <- matrix(0, nrow = length(celldata[, 1]), ncol = 2)
  
  for (i in seq_along(yield)) {
    
    tic()
    
    output <- mussel_odeSolve(i, celldata, days)
    TM <- output$TM
    Mwet <- output$Mwet
    yield[i] <- TM[length(TM)]
    Wets[i, 1:length(Mwet)] <- Mwet
    ProblemCells[i, 1] <- i
    if (length(TM) < harvestcycle + 2) {
      ProblemCells[i, 2] <- 1
    }
    
    toc()
    
  }
  # save('ProblemCells.csv', ProblemCells) #commenting out unless we decide we need to write a csv
  lookuptable <- cbind(celldata[, 1:4], yield, yield/1000)
  # save('Yield.csv', lookuptable) #commenting out unless we decide we need to write a csv
} else {
  
  toc()
  
  # Single Cell
  cellno <- as.integer(readline(prompt = 'Choose a cell (1-1134)\n'))
  assert(cellno <= length(celldata[, 1]) && cellno >= 1, 'Please enter a number between 1 and 1134')
  tic()
  output <- mussel_odeSolve(cellno, celldata, days)
  T <- output$T
  TM <- output$TM
  Indiv <- output$Indiv
  MV <- output$MV
  ME <- output$ME
  MR <- output$MR
  M <- output$M
  Mwet <- output$Mwet
  LW <- output$LW
  Fdens <- output$Fdens
  F_Ambient <- output$F_Ambient
  f <- output$f
  Temperature <- output$Temperature
  MixedLayerDepth <- output$MixedLayerDepth
  CurrentSpeed <- output$CurrentSpeed
  outputs <- cbind(T, Mwet, LW, f, Fdens, F_Ambient, TM)
  
  toc()
  
  # Plots
  # Ans2 <- readline(prompt = 'Plot results? (Y/N)\n')
  # assert(Ans2 == 'Y' || Ans2 == 'N', 'Please enter "Y" or "N"')
  # if (Ans2 == 'Y') {
  #   musselplot(T, TM, f, Mwet, LW, Fdens, F_Ambient, Temperature, MixedLayerDepth, CurrentSpeed)
  # }
}
```

