---
title: "Sensitivity Testing"
author: 'By: Claire Gonzales'
date: "2024-08-10"
output: 
  html_document: 
    theme: lumen
    toc: yes
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)

library(tidyverse)
library(here)
library(stats)
library(ggplot2)
library(stats)
```


## Read and wrangle in data
```{r}

output_main <- read.csv(here("data","bivalve_model","LookUpTable_201416.csv")) %>% 
  dplyr::select("site", "long", "lat", "yield")
output_s1 <- read.csv(here("data","bivalve_model","LookUpTable_s1.csv"))
output_s2 <- read.csv(here("data","bivalve_model","LookUpTable_s2.csv"))
output_s3 <- read.csv(here("data","bivalve_model","LookUpTable_s3.csv"))

```

```{r}
s1 <- output_s1 %>% 
  mutate(s1_yield = yield) %>% 
  dplyr::select("site", "long", "lat", "s1_yield")

s2 <- output_s2 %>% 
  mutate(s2_yield = yield) %>% 
  dplyr::select("site", "long", "lat", "s2_yield")

s3 <- output_s3 %>% 
  mutate(s3_yield = yield) %>% 
  dplyr::select("site", "long", "lat", "s3_yield")
```

Merging the 3 frames. Format will be wide so then we will make it longer.
```{r}
wide1 <- merge(output_main, s1, by = c("site", "long", "lat"), all = TRUE)

wide2 <- merge(s2, s3, by = c("site", "long", "lat"), all = TRUE)

wide <- merge(wide1, wide2, by = c("site", "long", "lat"), all = TRUE)
```

```{r}
alldata <- wide %>% 
  pivot_longer(yield:s3_yield,
               names_to = "test",
               values_to = "yield")
```

## Visualizations

```{r}
##boxplot and violin plot
ggplot(data = alldata, aes(x = test, y = yield, fill = test)) +
  geom_boxplot() +
  #geom_jitter(color="black", size=0.4, alpha=0.9) +
  theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
  theme_minimal()

ggplot(data = alldata, aes(x = test, y = yield, fill = test)) +
  geom_violin() +
  #geom_jitter(color="black", size=0.4, alpha=0.9) +
  theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
  theme_minimal()
```

## ANOVA

```{r}
summary(alldata)

```

```{r}
aov <- aov(yield ~ test, 
           data = alldata)

summary(aov)
```

```{r}
hist(aov$residuals)

ggplot(data = alldata, aes(sample = yield)) +
  geom_qq() +
  facet_wrap( ~ test) +
  theme_minimal()
```

